export default [
  {
    id: 1,
    title: "فوکاچا",
    ingredients: "نان ایتالیایی،روغن زیتون،رزماری",
    price: 78000,
    img: "../assets/focaccia.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "پیتزا مارگاریتا",
    ingredients: "پنیر موزارلا،گوجه،ریحان",
    price: 132000,
    img: "../assets/margherita.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "پیتزا اسنفاج",
    ingredients: "پنیر موزارلا،پنیر ریکوتا،اسفناج،گوجه",
    price: 149000,
    img: "../assets/spinaci.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "پیتزا سبزیجات",
    ingredients: "پنیر موزارلا،گوجه،قارچ،پیاز",
    price: 163000,
    img: "../assets/funghi.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "پیتزا سالامینو",
    ingredients: "پنیر موزارلا،پپرونی،گوجه",
    price: 158000,
    img: "../assets/salamino.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "پیتزا پرشودو",
    ingredients: "پنیر موزارلا،گوشت،پنیر بروتا،گوجه",
    price: 218000,
    img: "../assets/prosciutto.jpg",
    amount: 1,
  },
];
